### PR TITLE
add mee6 like rank card

### PR DESCRIPTION
**Pull request by timothypidashev**

### CODE REVIEW

**Comment by timothypidashev** [comment]
made this pr for issue https://github.com/DoobDev/Doob/issues/221

**Review by mmattbtw — CHANGES_REQUESTED** [review]
line 255, change from `context` to `ctx`, other then that it lgtm!

ignore the codacy+codefactor alerts btw :D

**Comment by timothypidashev** [comment]
Alr sounds great!

**Comment by mmattbtw** [comment]
last minute nitpick (sorry lol)

make sure to
- [ ] change the version number in `LAUNCHER.py`
- [ ] create a new entry in `CHANGELOG.md`

**Comment by timothypidashev** [comment]
I have tried to fix this lol I’m not the guy I wish I could tho sorry m8 I have no idea where to begin

**Review by timothypidashev — COMMENTED** [review]
Alr I changes submitted

**Review by mmattbtw — APPROVED** [review]
LGTM! will test and merge tonight!

**Review by timothypidashev — COMMENTED** [review]
Ready to merge

**Comment by timothypidashev** [comment]
Keep in mind that the exp needed to reach next level is a static 1000 right now. That’s the only thing I couldn’t figure out. Issue #221

**Comment by mmattbtw** [comment]
I'm going to be closing this and not accepting this, due to the design and code not being up to standard.

Thank you for your time.

**Comment by timothypidashev** [comment]
Uhm automation closed the pr lmao

**Pull request closed without merging**
