### PR TITLE
➕Add 1/1000 chance for coin to land on side

### LINKED ISSUE #185: Include a 1/1000 chance of the coin landing on its side
`Issue Created via Doob for Discord`

### PR DESCRIPTION
**Pull request by AndyThePie**
> the coin flip command now has a 1/1000 chance of landing on its side. pain peko.

closes #185, i guess

basically, generate a random float, if said float is less than [or equal to] 0.001, send "The coin landed on its side..."

i think it works. i'm 515 flips in and i still haven't gotten the message yet...
try at your own risk :3

### CODE REVIEW

**Comment by AstroOrbis** [comment]
Make a command that flips x amount of coins, and gives the output (Side only appears if at least 1 flipped on the side): `Heads: x | Tails: x | Side: x`

**Comment by AstroOrbis** [comment]
Just ideas :3

**Comment by AndyThePie** [comment]
> Make a command that flips x amount of coins, and gives the output (Side only appears if at least 1 flipped on the side): `Heads: x | Tails: x | Side: x`

You're better off filing this as a feature request / issue - not a comment on a pull request (which I have done for you, see #192 ). Also worth noting - this isn't my project, just a pull request of mine. (^^);

**Review by mmattbtw — APPROVED** [review]
LGTM! tysm for your contribution

**Pull request merged**
